// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQ4oeJsZsFdbbwLcwg61T6QlwLliCqm4',
    appId: '1:738041313824:web:55191d938a49c6c6b1da45',
    messagingSenderId: '738041313824',
    projectId: 'bill-buddy-93c8a',
    authDomain: 'bill-buddy-93c8a.firebaseapp.com',
    storageBucket: 'bill-buddy-93c8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWTMQ69-zUarpjuIOA-IhkbYrKy1ONXM',
    appId: '1:738041313824:android:3cb52822e8c1ffefb1da45',
    messagingSenderId: '738041313824',
    projectId: 'bill-buddy-93c8a',
    storageBucket: 'bill-buddy-93c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLfDZENYVZHHGtzPQJd1mvoDOdSv1SrvM',
    appId: '1:738041313824:ios:dbaf28e43291e781b1da45',
    messagingSenderId: '738041313824',
    projectId: 'bill-buddy-93c8a',
    storageBucket: 'bill-buddy-93c8a.firebasestorage.app',
    androidClientId:
        '738041313824-7459iegv8a1e79fuob12lf01etg10hht.apps.googleusercontent.com',
    iosClientId:
        '738041313824-84thevk9ecgqcbhahaipbsgmnc4ef909.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.billBuddy',
  );
}
